version: 2
updates:
  # Configuración para actualizaciones de dependencias de Maven
  - package-ecosystem: "maven"
    directory: "/"  # Ruta del directorio donde está el archivo pom.xml
    schedule:
      interval: "weekly"  # Puede ser daily, weekly, monthly
    commit-message:
      prefix: "fix"  # Prefijo del mensaje de commit
    allow:
      - dependency-type: "direct"  # Solo actualiza dependencias directas
